### ISSUE TITLE
Requires a better picture of Gitline from begineer's perspective.

### ISSUE THREAD

**Issue by Verma-Ashish13** [letimome/GitLine#12]
Hello Sir and Ma'am,
I am Ashish, a 3rd year undergraduate pursuing btech in CSE from Indian institute of information technology Sricity, India. My btech project is to tune github for SPL. I was going through your publication** "Tuning Github for SPL development: branching  models and repository operations for product engineers"** and didn't get a clear picture because of being new in the domain. Can you please tell me where should I look to use your tool for better understanding. I will very thankful if you share some insight on the topic from the beginners perspective.
I look forward for your consideration.
Thanks,
Regards,
Ashish

**Comment by letimome** [comment]
Dear Ashish,

First of all thanks for your interest in our work, I am glad you contact us. 
Regarding your request, I will sum up the highlights of our work and tool Gitline.

**BACKGROUND**

- Our tool works for SPLs implemented in Feature Oriented Programing (FOP). There are plenty of ways to implement an SPL, e.g, preprocessor-based, FOP, AOP, parameters… To select one out of them is a matter of taste. Each one has its PROS and CONS…  The following book provides a nice SPL insight on SPLs: http://link.springer.com/book/10.1007%2F978-3-642-37521-7 

- As you know SPL development is divided into Domain Engineering (the ones building the core assets) and Application Engineering (the ones building the products by reusing the core assets). With regard to Version Control Systems (VCSs), this is equated as having one repository for Domain Engineers, a.k.a. Core Asset repository,  and several product repositories, one per each project to be built. Additionally, Feature Models, serve to aid Application Engineers on selecting the features they need for their products.

- Our tool GitLine, is a firefox extension FOR Application Engineers (AE). The tool helps AEs in creating a product repository from a core asset repo, and synching with the core asset repository.

**THE TOOL**
To use our tool follow the instruction on http://letimome.github.io/GitLine/. A more detailed process follows:	

1. To play with the tool on your own, it is best you create two different Github accounts: one for the domain engineer, and another one for  application engineer. 

- Create a Github account for the domain engineer: e.g., domainUser. This account would host the “Core Assets repository”.  If you don’t have yourself an SPL implemented, log into github as the domainUser  and fork my core asset repository: https://github.com/letimome/VODPlayer-CoreAssets. 

- Create another github account for the application engineers. e.g. applicationUser. Within this account generate a github API TOKEN. This TOKEN will be used by our tool GitLine. Here is how to create a token in github https://help.github.com/articles/creating-an-access-token-for-command-line-use/. 

2. Then, install our tool (which is a FireFox AddOn) in Firefox v37. Make sure you install our tool in firefox version 37 and not into more recent ones. I have not tested it for versions younger than 37.0.

- Download the ZIP https://github.com/letimome/GitLine and extract the the ZIP into your firefox extension folder.  To know where your extension folder is in your computer go to firefox profile folder: http://ccm.net/faq/1934-firefox-finding-the-profile-folder and inside there is a extension folder. Extract the zip here. You should now have a folder named “scxmlGitDelta@onekin.org” inside extension folder.

- Inside “scxmlGitDelta@onekin.org”  folder, go to file content/githubdeltas.js, find the function DeltaUtils.getUserAccessToken and paste there the TOKEN you have previously generated when creating the Github account for the application engineer.

- Next, in Firefox URL bar type "about:config". Set the following values to false: security.csp.enable=false, and security.mixed-content.block_active_content=false.

- If you restart firefox, and type “about:addons” in the URL bar, you should see that GitLine extension is installed.

3. Playing with GitLine

- Now, if you log into github as applicationUser and go to domainUser/VODPlayer-CoreAssets, you should see a new button “Product Fork”. This is the functionality to create product repository into the application engineer account. As explained in http://letimome.github.io/GitLine/ - Product Fork

- To perform update propagation, make some changes in your core asset repository (logged as domainUser). Make sure the master branch has new updates. Then, as applicationUser, checkout the update.updates branch and you will see the “Update Propagation” button. Click on it to sync the product repository. Follow the same idea for “Feedback propagation”.

I hope i gave you a clearer view. If you have further inquiries or find difficulties on installing/using our tool feel free to post them here :)

**Comment by letimome** [comment]
A new version of GitLine is released! Maybe you want have a look at it.

Best,
Leticia
